server:
  port: 9090
  servlet:
    context-path: /dsas
  tomcat:

      uri-encoding: UTF-8

mybatis:

  config-location: classpath:mybatis/mybatis.xml    # mybatis配置文件所在路径

  type-aliases-package: com.unistrong.geotsd.datasource.data       # 定义所有操作类的别名所在包

  mapper-locations:                                     # 所有的mapper映射文件

  - classpath:mybatis/mapper/**/*.xml

spring:

  datasource:

    type: com.alibaba.druid.pool.DruidDataSource   # 配置当前要使用的数据源的操作类型

    driver-class-name: com.p6spy.engine.spy.P6SpyDriver      # 配置的驱动程序类
    #driver-class-name: org.postgresql.Driver

    url: jdbc:p6spy:postgresql://192.168.251.78:1328/dsas   # 数据库连接地址
    #url: jdbc:postgresql://192.168.251.78:1328/dsas

    username: beyondb                                  # 数据库用户名

    password: 123456                            # 数据库连接密码

    dbcp2:                                          # 进行数据库连接池的配置

      min-idle: 5                                   # 数据库连接池的最小维持连接数

      initial-size: 5                               # 初始化提供的连接数

      max-total: 50                                  # 最大的连接数

      max-wait-millis: 200                          # 等待连接获取的最大超时时间

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  servlet:
      multipart:
        max-file-size: 30MB
        max-request-size: 30MB


#分页的配置
pagehelper:
    helperDialect: postgresql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql

logging:

  config: classpath:log4j2-spring.xml
